version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  go-demo:
    container_name: go-demo
    env_file: .env
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app%
    depends_on:
      - postgres

volumes:
  db-data:
