version: "3.7"

services:
  go-demo:
    env_file: .env
    build: ./
    ports:
      - "8080:8080"
    volumes:
      - ./:/app%

  postgres:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
